export interface IEmailIncidentList{
    sLaHrs: number;
    id:number,
    isChecked:boolean,
    conversationId:string,
    mailSubject:string,
    creationTime:Date,
    mailRecievedTime:Date,
    mailFrom:string,
    mailCC:string,
    attachment:boolean,
    tat:string,
    assignedOn:Date,
    isAssignToTeam:boolean,
    assignToTeamId:number,
    completedOn:Date,
    incidentId:string,
    autoReply:boolean,
    conversationThreadId:string,
    isParent:boolean,
    userId:string,
    classificationId:string,
    mailBoxId:string,
    statusId:string,
    sentiment:string,
    teamName: string,
    priorityFlag: number
}